---
title: "RelativeAbundances"
author: "A.DeMartin"
date: "2025-02-21"
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---
## load packages
```{r load packages, warning=FALSE, include=FALSE}
library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
```

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## load file
```{r load merged file}
##load merged file 
fileNam <- "/Users/immbio/Desktop/Project/Angelina/CarTransLateRej/data/CarTransLateRej_allmerged_seurat.rds"
seuratM <- readRDS(fileNam)
```

##set color vectors 
```{r set color vector}
colclusterName <- c("#67001f", "#D53E4F", "#f4a582", "#003c30","#01665e","#66C2A5", "#3288BD","#BEAED4", "#c7eae5","#355C7D","#202547","#628395","#8c510a", "#B09C85", "#4e5a4c","#725663FF","#B45B5C","#FEE08B")
names(colclusterName) <- c("CM1","CM2","CM3","Fb1","Fb2","Int1", "Int2", "Int3","PerivFb","VSMC","BEC1", "BEC2","LEC","NC","Int4","AdipoC","Mph","Tcell")

coldiseaseCond <- c("#dfc27d","#BE3144","#f4a582","#B45B5C","#8c510a","#202547","#355C7D","#779d8d", "#3288BD")
names(coldiseaseCond) <- c("healthy", "visit1", "visit2" ,"visit3", "visit4", "visit5", "visitX1", "visitX2", "visitX3")
```

## order datasets
```{r order, include=FALSE}
Idents(seuratM) <- seuratM$clusterName
seuratM$clusterName <- factor(seuratM$clusterName, levels=c("CM1","CM2","CM3","Fb1","Fb2","Int1", "Int2", "Int3","PerivFb","VSMC","BEC1", "BEC2","LEC","NC","Int4","AdipoC","Mph","Tcell"))
Idents(seuratM) <- seuratM$clusterName
table(seuratM$clusterName)

Idents(seuratM) <- seuratM$diseaseCond
seuratM$diseaseCond <- factor(seuratM$diseaseCond, levels=c("healthy", "visit1", "visit2" ,"visit3", "visit4", "visit5", "visitX1", "visitX2", "visitX3"))
Idents(seuratM) <- seuratM$diseaseCond
table(seuratM$diseaseCond)
```

```{r abundance diseaseCond, fig.height=8, fig.width=10}
###diseaseCond
datList <- NULL
for(con in unique(seuratM$diseaseCond)){
  seuratSub <- subset(seuratM, diseaseCond==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$clusterName)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(diseaseCond=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

orddiseaseCond <- c("healthy", "visit1", "visit2" ,"visit3", "visit4", "visit5", "visitX1", "visitX2", "visitX3")

## plot abundance
ggbarplot(dat_all, x= "diseaseCond", y= "percent", fill = "Var1", legend = "right",  palette = colclusterName, legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(limits=orddiseaseCond)
```

```{r abundance patient_diseaseCond, fig.height=8, fig.width=10}
###patient_diseaseCond
datList <- NULL
for(con in unique(seuratM$patient_diseaseCond)){
  seuratSub <- subset(seuratM, patient_diseaseCond==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$clusterName)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(patient_diseaseCond=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

ordpatient_diseasecond <- unique(seuratM$patient_diseaseCond)[order(
  !grepl("healthy", unique(seuratM$patient_diseaseCond)),  # "HH" first (FALSE is sorted before TRUE)
  !grepl("visit1", unique(seuratM$patient_diseaseCond)),  # "visit1" second
  !grepl("visit2", unique(seuratM$patient_diseaseCond)),  # "visit2" third
  !grepl("visit3", unique(seuratM$patient_diseaseCond)),  # "visit3" third
  !grepl("visit4", unique(seuratM$patient_diseaseCond)),  # "visit4" third
  !grepl("visit5", unique(seuratM$patient_diseaseCond)),  # "visit5" third
  !grepl("visitX1", unique(seuratM$patient_diseaseCond)),  # "visitX1" third
  !grepl("visitX2", unique(seuratM$patient_diseaseCond)),  # "visitX2" third
   !grepl("visitX3", unique(seuratM$patient_diseaseCond)),  # "visitX3" third
  unique(seuratM$patient_diseaseCond)  # Alphabetical order within groups
)]

## plot abundance
ggbarplot(dat_all, x= "patient_diseaseCond", y= "percent", fill = "Var1", palette = colclusterName, legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(limits=ordpatient_diseasecond)


ordpatient_diseasecond <- unique(seuratM$patient_diseaseCond)[order(
  !grepl("healthy", unique(seuratM$patient_diseaseCond)),  # "HH" first (FALSE is sorted before TRUE)
  !grepl("CarTransPat4", unique(seuratM$patient_diseaseCond)),  # CarTransPat4 second
  !grepl("CarTransPat6", unique(seuratM$patient_diseaseCond)),
  !grepl("CarTransPat7", unique(seuratM$patient_diseaseCond)),
  !grepl("CarTransPat18", unique(seuratM$patient_diseaseCond)),  
  unique(seuratM$patient_diseaseCond)  # Alphabetical order within groups
)]

## plot abundance
ggbarplot(dat_all, x= "patient_diseaseCond", y= "percent", fill = "Var1", palette = colclusterName, legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(limits=ordpatient_diseasecond)
```

## fractions according to patients&disease cond
```{r fractions, fig.height=8, fig.width=10}
##set order
seuratM$diseaseCond <- factor(seuratM$diseaseCond, levels= c("healthy", "visit1", "visit2" ,"visit3", "visit4", "visit5", "visitX1", "visitX2", "visitX3"))

## 1. create data.frame with cluster counts per patient
## change "RNA_snn_res.0.25" to subset/cluster you're interested in ...
datFrac <- data.frame(table(seuratM$patient_diseaseCond, seuratM$clusterName))
colnames(datFrac) <- c("patient_diseaseCond", "subset", "cnt")

## 2. get total counts per patient to compute relative abundances from
## I added cond here as grouping variable for the plotting later ...
datSumPat <- data.frame(table(seuratM$patient_diseaseCond, seuratM$diseaseCond)) %>% 
  filter(Freq >0)
colnames(datSumPat) <- c("patient_diseaseCond", "diseaseCond", "cntPatTot")

## 3. join data.frames to compute rel abundances per patient
datFracSum <- datFrac %>% left_join(., datSumPat, by = "patient_diseaseCond") %>% 
  mutate(relCnt = cnt/cntPatTot)

## plot barplot with abundances for each subset grouped by cond
ggbarplot(datFracSum, x = "subset", y = "relCnt",
          fill = "diseaseCond", color = "diseaseCond",
          palette = coldiseaseCond,
          add = c("mean_se", "dotplot"),
          add.params = list(color="black", fill="diseaseCond", size=0.2),
          position = position_dodge(0.9),
          xlab = "subset",
          ylab = "relative abundance",
          legend = "right",
          legend.title = "") +
  rotate_x_text(angle = 90) 

## plot barplot with abundances for individual subsets
Idents(seuratM) <- seuratM$clusterName
clusterVec <- levels(seuratM)
createClusterPlot <- function(cluster) {
  datFracSumC <- datFracSum %>% filter(subset == cluster)

  ggbarplot(datFracSumC, x = "diseaseCond", y = "relCnt",
            fill = "diseaseCond", color = "diseaseCond",
            palette = coldiseaseCond,
            add = c("mean_se", "dotplot"),
            size = 5,
            add.params = list(color = "black", fill = "diseaseCond"),
            position = position_dodge(0.9),
            xlab = cluster,
            ylab = "relative abundance",
            legend = "right",
            legend.title = "") +
    stat_compare_means(method = "kruskal.test", label.y = 0.0)
}
lapply(clusterVec, createClusterPlot)
```

## session info
```{r date and session info}
date()
sessionInfo()
```
